# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subGenProto.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11subGenProto.proto\x12\x0bsubGenProto\"\x1b\n\nInputVideo\x12\r\n\x05video\x18\x01 \x01(\x0c\"\x1c\n\x0bOutputVideo\x12\r\n\x05video\x18\x01 \x01(\x0c\x32R\n\x11SubtitleGenerator\x12=\n\x08Generate\x12\x17.subGenProto.InputVideo\x1a\x18.subGenProto.OutputVideob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subGenProto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUTVIDEO']._serialized_start=34
  _globals['_INPUTVIDEO']._serialized_end=61
  _globals['_OUTPUTVIDEO']._serialized_start=63
  _globals['_OUTPUTVIDEO']._serialized_end=91
  _globals['_SUBTITLEGENERATOR']._serialized_start=93
  _globals['_SUBTITLEGENERATOR']._serialized_end=175
# @@protoc_insertion_point(module_scope)
