// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc1
// source: videoExtractor.proto

package videoExtractor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoStreamServiceClient is the client API for VideoStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoStreamServiceClient interface {
	GetVideoBuffer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type videoStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoStreamServiceClient(cc grpc.ClientConnInterface) VideoStreamServiceClient {
	return &videoStreamServiceClient{cc}
}

func (c *videoStreamServiceClient) GetVideoBuffer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/videoExtractor.VideoStreamService/GetVideoBuffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoStreamServiceServer is the server API for VideoStreamService service.
// All implementations must embed UnimplementedVideoStreamServiceServer
// for forward compatibility
type VideoStreamServiceServer interface {
	GetVideoBuffer(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedVideoStreamServiceServer()
}

// UnimplementedVideoStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoStreamServiceServer struct {
}

func (UnimplementedVideoStreamServiceServer) GetVideoBuffer(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoBuffer not implemented")
}
func (UnimplementedVideoStreamServiceServer) mustEmbedUnimplementedVideoStreamServiceServer() {}

// UnsafeVideoStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoStreamServiceServer will
// result in compilation errors.
type UnsafeVideoStreamServiceServer interface {
	mustEmbedUnimplementedVideoStreamServiceServer()
}

func RegisterVideoStreamServiceServer(s grpc.ServiceRegistrar, srv VideoStreamServiceServer) {
	s.RegisterService(&VideoStreamService_ServiceDesc, srv)
}

func _VideoStreamService_GetVideoBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoStreamServiceServer).GetVideoBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/videoExtractor.VideoStreamService/GetVideoBuffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoStreamServiceServer).GetVideoBuffer(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoStreamService_ServiceDesc is the grpc.ServiceDesc for VideoStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videoExtractor.VideoStreamService",
	HandlerType: (*VideoStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideoBuffer",
			Handler:    _VideoStreamService_GetVideoBuffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "videoExtractor.proto",
}
